### ISSUE TITLE
Docs: specify that the project name must be a valid S3 bucket name

### ISSUE THREAD

**Issue by massi-ang** [aws-samples/amazon-sagemaker-edge-defect-detection-computer-vision#1]
Using project name with capital letters causes the stack to fail because the S3 bucket name is invalid.

**Comment by licesonw** [comment]
Thanks Massimiliano, just updated the Readme with this [commit](https://github.com/aws-samples/amazon-sagemaker-edge-defect-detection-computer-vision/commit/9d1ef60a8513a08add3677613c867c7ddd92effb). Will also bake this into the CloudFormation template.
